version: '2.3'

services:
  hackathon:
    restart: always
    container_name: hackathon
    build:
      context: .
      dockerfile: Dockerfile
    image: hackathon:latest
    volumes:
      - .:/hackathon
    command: bash -c "gunicorn --access-logfile - -w 1 --bind 0.0.0.0:5000 app:app --timeout 15000"
    network_mode: host